---
- hosts: webservers
  become: yes
  remote_user: ubuntu
  tasks:
  - name: Instalando o NGINX
    apt:
      name: nginx
      state: latest
      update_cache: yes

  - name: Iniciando o NGINX
    service:
      name: nginx
      state: started

  - name: Habilitando o start do Nginx no boot
    service:
      name: nginx
      enabled: yes

  - name: Copiando html
    copy:
      src: index.html
      dest: /var/www/html/index.html

  - name: Copiando nginx.conf
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    notify: Restartando o Nginx
  
  handlers:
  - name: Restartando o Nginx
    service:
      name: nginx
      state: restarted
