- name: Download HELM
  get_url:
    url: "{{ helm_url }}"
    dest: /tmp/get_helm.sh
    mode: 0775
  ignore_errors: true
  register: download

#- name:
#  debug: var=download

- name: Instalando HELM
  shell:
    /tmp/get_helm.sh
  when:
    - download.failed|bool == false
  register: install_helm

- name:
  debug: var=install_helm
