- name: helm add repo
  shell: helm repo add stable {{ url_repo_helm }}
  register: prometheus_add_repo

- name: helm update
  shell: helm repo update
  register: prometheus_repo_update

- name: Instalando o promotheus operator
  shell: helm install {{ deploy_promotheus }}
  register: prometheus_install

