Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.provision "shell", path: "install.sh"
    #config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "public_network", bridge: "Intel(R) Wireless-AC 9462"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.name   = "tform"
        vb.cpus    = 1
        
      end
end